micronaut:
  application:
    name: locadoraCar
#My SQL
datasources:
  default:
    url: jdbc:mysql://localhost:3306/livraria?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456
    dialect: MYSQL
    schema-generate: CREATE_DROP
jpa:
  default:
    entity-scan:
      packages: 'com.erick.adapters.persistence.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
